TESTS WITH ERRORS 
-------------------------------
TESTS FAILED  
test07 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 132, in test07
    self.checkMovables(th, expectedMovables)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 22, in checkMovables
    'can be found: "%s"' % [str(x) for x in expected])
AssertionError: False is not true : None of the expected Facts with MOVABLE predicate can be found: "['fact: (movable tile4 pos2 pos1 pos3 pos1)', 'fact: (movable tile8 pos3 pos2 pos3 pos1)']"

test09 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 163, in test09
    self.checkMovables(th, expectedMovables)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/world-building/gradingtests.py", line 26, in checkMovables
    'cannot be found in KB: "%s"' % str(e))
AssertionError: False is not true : Expected Fact with MOVABLE predicate cannot be found in KB: "fact: (movable tile8 pos1 pos2 pos2 pos2)"

-------------------------------
TESTS SKIPPED 
-------------------------------
